"""
scenic_module.scenario_generator
==================================
Generates ``.scenic`` scenario files from sweep-identified boundary and
hazardous points.

The generated files follow the same structure and property-name vocabulary
as the hand-written scenarios in ``systems_engineering/06_safety/scenarios/``
so that they can be used interchangeably with the Scenic probabilistic
programming tool.

Output directory: ``systems_engineering/06_safety/scenarios/sweep/``

File naming::

    sweep_H01_boundary_001.scenic   # near-threshold boundary point
    sweep_H02_hazardous_001.scenic  # constraint-violating point
    sweep_multi_hazardous_001.scenic  # multiple constraints violated

Each file is standalone and valid Scenic syntax.  No Scenic library
installation is required to *generate* the files; it is only needed to
*run* them.
"""

from __future__ import annotations

import textwrap
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

from .sweep import ScenarioPoint, SweepResult
from .parameter_space import ALL_PARAMETERS


# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

_THIS_DIR  = Path(__file__).resolve().parent
_SCENARIOS = _THIS_DIR.parent / "scenarios"
_SWEEP_DIR = _SCENARIOS / "sweep"


# ---------------------------------------------------------------------------
# Scenic file template helpers
# ---------------------------------------------------------------------------

# Map from constraint ID to the primary scenario tag (used in the Scenic
# ``scenario`` declaration name and in the output filename).
CONSTRAINT_TO_TAG: dict[str, str] = {
    "H-01":      "motor_stall",
    "H-02":      "tilt_risk",
    "H-03":      "battery_low",
    "H-03-warn": "battery_low",
    "H-04":      "comm_loss",
    "H-05":      "nominal_traverse",
}


def _constraint_label(cids: list[str]) -> str:
    """Short label for filename — first violated constraint or 'multi'."""
    if not cids:
        return "safe"
    if len(cids) == 1:
        return cids[0].lower().replace("-", "")
    return "multi"


def _format_param_block(params: dict[str, float]) -> str:
    """
    Return a Scenic ``param`` block string with one param per line.
    Only parameters that exist in ALL_PARAMETERS are emitted.
    """
    lines: list[str] = []
    for key, val in params.items():
        if key not in ALL_PARAMETERS:
            continue
        p = ALL_PARAMETERS[key]
        # Format value with sensible precision
        if abs(val) >= 1.0:
            fmt = f"{val:.3f}"
        else:
            fmt = f"{val:.4f}"
        lines.append(f"    {key}: {fmt},  # {p.unit}")
    return "\n".join(lines)


def _format_threshold_comment(violated: list[str]) -> str:
    """Human-readable constraint violation summary for Scenic file header."""
    if not violated:
        return "# No constraints violated — boundary point (near threshold)"
    lines = ["# Violated constraints:"]
    for cid in violated:
        p_list = [p.key for p in ALL_PARAMETERS.values() if cid in p.constraint_refs]
        lines.append(f"#   {cid}: primary params = {', '.join(p_list)}")
    return "\n".join(lines)


def _scenic_file_content(
    point:      ScenarioPoint,
    label:      str,
    seq_num:    int,
    point_type: str,    # "boundary" or "hazardous"
) -> str:
    """Render a complete Scenic scenario file for one sweep point."""

    scenario_name = f"sweep_{label}_{point_type}_{seq_num:03d}"
    violated_str  = ", ".join(point.violated_constraints) or "none"
    constraint_cmt = _format_threshold_comment(point.violated_constraints)
    param_block    = _format_param_block(point.params)
    haz_pct        = f"{point.hazard_level * 100:.1f}"

    # Which hand-written scenario does this correspond to?
    base_scenario = "nominal_traverse"
    if point.violated_constraints:
        tag = CONSTRAINT_TO_TAG.get(point.violated_constraints[0], "nominal_traverse")
        base_scenario = tag

    content = textwrap.dedent(f"""\
        \"\"\"
        Sweep-generated Scenic scenario: {scenario_name}
        =================================================
        Generated by: scenic_module.scenario_generator
        Source sweep: parametric OA/OE sweep

        Point type        : {point_type}
        Hazard level      : {haz_pct} %
        Violated          : {violated_str}
        Sweep index       : {point.index}

        {constraint_cmt}

        This file is standalone valid Scenic syntax.
        To run: scenic {scenario_name}.scenic -S 1 --simulate
        \"\"\"

        # ── Scenic model import ────────────────────────────────────────────
        model scenic.simulators.ros.ROSModel

        # ── Scenario parameters ────────────────────────────────────────────
        # Values sampled from OSR OA/OE parameter space by sweep engine.
        # Ranges are narrow bands around the sweep sample for Scenic to
        # explore the immediate neighbourhood of this boundary/hazard point.

        param osr_scenario = globalParameters.get("osr_scenario", "{base_scenario}")

        scenario {scenario_name}():
            setup:
                # ── Sampled OA/OE values ───────────────────────────────────
                osr_params = dict(
        {param_block}
                )

                # ── Narrow-band Scenic distributions around sweep point ────
    """)

    # Add one Range() distribution per sampled param (±5 % of physical range)
    dist_lines: list[str] = []
    for key, val in point.params.items():
        if key not in ALL_PARAMETERS:
            continue
        p = ALL_PARAMETERS[key]
        span = max(abs(p.phys_max - p.phys_min) * 0.05, 1e-6)
        lo = max(p.phys_min, val - span)
        hi = min(p.phys_max, val + span)
        dist_lines.append(
            f"                {key} = Range({lo:.4f}, {hi:.4f})  # {p.unit}"
        )
    content += "\n".join(dist_lines)

    content += textwrap.dedent(f"""

            compose:
                # Expose all parameters as Scenic global parameters so the
                # ROS adapter can read them at runtime.
                for key, val in osr_params.items():
                    require globalParameters.get(key, val) == val

            record final:
                hazard_level: {point.hazard_level:.4f}
                violated_constraints: "{violated_str}"
    """)

    return content


# ---------------------------------------------------------------------------
# Generator class
# ---------------------------------------------------------------------------

@dataclass
class GeneratorConfig:
    """Configuration for Scenic file generation from a sweep result."""

    output_dir:       Path    = field(default_factory=lambda: _SWEEP_DIR)
    max_boundary:     int     = 20    # max boundary scenario files to write
    max_hazardous:    int     = 20    # max hazardous scenario files to write
    min_hazard_level: float   = 0.05  # minimum hazard score to include
    overwrite:        bool    = True


class ScenarioGenerator:
    """Generates ``.scenic`` files from a :class:`~scenic_module.sweep.SweepResult`."""

    def __init__(self, config: Optional[GeneratorConfig] = None) -> None:
        self.cfg = config or GeneratorConfig()

    def generate(self, result: SweepResult) -> list[Path]:
        """
        Write Scenic files for the boundary and hazardous points in *result*.

        Returns
        -------
        list of :class:`pathlib.Path`
            Paths of the files that were written.
        """
        self.cfg.output_dir.mkdir(parents=True, exist_ok=True)
        written: list[Path] = []

        # --- Hazardous points (sorted by severity, highest first) ----------
        haz_sorted = sorted(
            [p for p in result.hazardous_points
             if p.hazard_level >= self.cfg.min_hazard_level],
            key=lambda p: p.hazard_level,
            reverse=True,
        )[: self.cfg.max_hazardous]

        for seq, pt in enumerate(haz_sorted, start=1):
            label = _constraint_label(pt.violated_constraints)
            fname = f"sweep_{label}_hazardous_{seq:03d}.scenic"
            path  = self.cfg.output_dir / fname
            if not self.cfg.overwrite and path.exists():
                continue
            content = _scenic_file_content(pt, label, seq, "hazardous")
            path.write_text(content, encoding="utf-8")
            written.append(path)

        # --- Boundary points (sorted by closeness to threshold) -----------
        bnd_sorted = sorted(
            result.boundary_points,
            key=lambda p: p.hazard_level,
            reverse=True,
        )[: self.cfg.max_boundary]

        for seq, pt in enumerate(bnd_sorted, start=1):
            label = _constraint_label(pt.violated_constraints) if pt.violated_constraints else "boundary"
            fname = f"sweep_boundary_{seq:03d}.scenic"
            path  = self.cfg.output_dir / fname
            if not self.cfg.overwrite and path.exists():
                continue
            content = _scenic_file_content(pt, label, seq, "boundary")
            path.write_text(content, encoding="utf-8")
            written.append(path)

        return written

    def generate_worst_per_constraint(self, result: SweepResult) -> list[Path]:
        """Write one Scenic file for the worst-margin point of each constraint.

        This ensures at least one scenario per hazard category is generated,
        regardless of the max_hazardous limit.
        """
        self.cfg.output_dir.mkdir(parents=True, exist_ok=True)
        written: list[Path] = []

        worst = result.worst_per_constraint()
        for cid, pt in worst.items():
            label = cid.lower().replace("-", "")
            fname = f"sweep_{label}_worst.scenic"
            path  = self.cfg.output_dir / fname
            content = _scenic_file_content(pt, label, 0, "hazardous")
            path.write_text(content, encoding="utf-8")
            written.append(path)

        return written


# ---------------------------------------------------------------------------
# Convenience function
# ---------------------------------------------------------------------------

def generate_scenarios(
    result:       SweepResult,
    output_dir:   Optional[Path] = None,
    max_boundary: int  = 20,
    max_haz:      int  = 20,
    worst_only:   bool = False,
) -> list[Path]:
    """One-liner: generate Scenic files from a sweep result.

    Parameters
    ----------
    result:
        Output of :class:`~scenic_module.sweep.SweepEngine.run`.
    output_dir:
        Directory to write ``.scenic`` files.  Defaults to
        ``scenarios/sweep/``.
    max_boundary, max_haz:
        Upper limits on number of files to write.
    worst_only:
        If True, only write the single worst-margin point per constraint.

    Returns
    -------
    list of :class:`pathlib.Path`
        Written file paths.
    """
    cfg = GeneratorConfig(
        output_dir    = output_dir or _SWEEP_DIR,
        max_boundary  = max_boundary,
        max_hazardous = max_haz,
    )
    gen = ScenarioGenerator(cfg)

    if worst_only:
        return gen.generate_worst_per_constraint(result)

    written  = gen.generate(result)
    written += gen.generate_worst_per_constraint(result)
    return written
